

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

# Load state history generated by the C++ simulator.
data = np.genfromtxt('output/simulation.csv', delimiter=',', names=True)

time = data['time']
x = data['x']
y = data['y']
z = data['z']
qw = data['qw']
qx = data['qx']
qy = data['qy']
qz = data['qz']


def create_rocket_geometry(length=5.0, diameter=1.0, num_sides=16):
    """Create a simple rocket centered at the vehicle CM and aligned with body +z."""
    radius = diameter / 2.0
    body_bottom = -0.5 * length
    body_top = 0.3 * length
    nose_tip_z = 0.5 * length

    angles = np.linspace(0.0, 2.0 * np.pi, num_sides, endpoint=False)

    bottom_ring = np.column_stack((
        radius * np.cos(angles),
        radius * np.sin(angles),
        np.full(num_sides, body_bottom),
    ))

    top_ring = np.column_stack((
        radius * np.cos(angles),
        radius * np.sin(angles),
        np.full(num_sides, body_top),
    ))

    nose_tip = np.array([0.0, 0.0, nose_tip_z])
    faces = []

    for i in range(num_sides):
        j = (i + 1) % num_sides
        faces.append([
            bottom_ring[i],
            bottom_ring[j],
            top_ring[j],
            top_ring[i],
        ])

    for i in range(num_sides):
        j = (i + 1) % num_sides
        faces.append([
            top_ring[i],
            top_ring[j],
            nose_tip,
        ])

    # Close the base of the rocket.
    faces.append(bottom_ring.tolist())

    return faces


def quaternion_to_rotation_matrix(w, x, y, z):
    """Convert the body-to-world quaternion into a rotation matrix."""
    return np.array([
        [1.0 - 2.0 * (y * y + z * z),
         2.0 * (x * y - w * z),
         2.0 * (x * z + w * y)],
        [2.0 * (x * y + w * z),
         1.0 - 2.0 * (x * x + z * z),
         2.0 * (y * z - w * x)],
        [2.0 * (x * z - w * y),
         2.0 * (y * z + w * x),
         1.0 - 2.0 * (x * x + y * y)],
    ])


def transform_rocket(faces, position, rotation_matrix):
    """Transform body-frame rocket vertices into the world frame."""
    return [
        [(rotation_matrix @ np.asarray(vertex)) + position for vertex in face]
        for face in faces
    ]


rocket_faces = create_rocket_geometry()

fig = plt.figure(figsize=(9, 7))
ax = fig.add_subplot(111, projection='3d')

# The actual trajectory is shown progressively during the animation.
trajectory_line, = ax.plot([], [], [], linewidth=1.5, label='Trajectory')

initial_rotation = quaternion_to_rotation_matrix(qw[0], qx[0], qy[0], qz[0])
initial_position = np.array([x[0], y[0], z[0]])
initial_faces = transform_rocket(rocket_faces, initial_position, initial_rotation)

rocket = Poly3DCollection(initial_faces, alpha=0.9, edgecolor='black', linewidth=0.3)
ax.add_collection3d(rocket)

time_text = ax.text2D(0.03, 0.95, '', transform=ax.transAxes)

# Give the vehicle enough visual room in x and y while retaining the full altitude range.
x_margin = 5.0
y_margin = 5.0
z_margin = 5.0

ax.set_xlim(np.min(x) - x_margin, np.max(x) + x_margin)
ax.set_ylim(np.min(y) - y_margin, np.max(y) + y_margin)
ax.set_zlim(np.min(z) - z_margin, np.max(z) + z_margin)

# Control the displayed box proportions so the nearly zero y-range does not
# flatten or wildly distort the vehicle geometry.
ax.set_box_aspect((1.0, 1.0, 2.5))
ax.view_init(elev=20, azim=-60)

ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.set_zlabel('Z (m)')
ax.set_title('6-DOF Flight Animation')
ax.legend()


def update(frame):
    rotation = quaternion_to_rotation_matrix(
        qw[frame], qx[frame], qy[frame], qz[frame]
    )
    position = np.array([x[frame], y[frame], z[frame]])

    transformed_faces = transform_rocket(rocket_faces, position, rotation)
    rocket.set_verts(transformed_faces)

    trajectory_line.set_data(x[:frame + 1], y[:frame + 1])
    trajectory_line.set_3d_properties(z[:frame + 1])

    time_text.set_text(f'Time: {time[frame]:.2f} s')

    return rocket, trajectory_line, time_text


# With dt = 0.01 s, a 10 ms interval plays approximately in real simulation time.
animation = FuncAnimation(
    fig,
    update,
    frames=len(time),
    interval=10,
    blit=False,
    repeat=True,
)

plt.show()